package com.wcsn.irislock.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "ALERT".
 */
public class Alert implements Serializable{

    public static final int ALERT_BATTERY = 0;
    public static final int ALERT_OPEN_DOOR = 1;
    public static final int ALERT_ERROR = 2;
    private Long id;
    private int type;
    /** Not-null value. */
    private String alertInfo;
    /** Not-null value. */
    private String time;
    /** Not-null value. */
    private String week;
    private String alertImage;

    public Alert() {
    }

    public Alert(Long id) {
        this.id = id;
    }

    public Alert(Long id, int type, String alertInfo, String time, String week, String alertImage) {
        this.id = id;
        this.type = type;
        this.alertInfo = alertInfo;
        this.time = time;
        this.week = week;
        this.alertImage = alertImage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getAlertInfo() {
        return alertInfo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAlertInfo(String alertInfo) {
        this.alertInfo = alertInfo;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getWeek() {
        return week;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWeek(String week) {
        this.week = week;
    }

    public String getAlertImage() {
        return alertImage;
    }

    public void setAlertImage(String alertImage) {
        this.alertImage = alertImage;
    }

}
