package com.wcsn.irislock.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.wcsn.irislock.bean.Authorize;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTHORIZE".
*/
public class AuthorizeDao extends AbstractDao<Authorize, Long> {

    public static final String TABLENAME = "AUTHORIZE";

    /**
     * Properties of entity Authorize.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property IsAuthorize = new Property(2, boolean.class, "isAuthorize", false, "IS_AUTHORIZE");
        public final static Property IsOpen = new Property(3, boolean.class, "isOpen", false, "IS_OPEN");
        public final static Property OpenTime = new Property(4, String.class, "openTime", false, "OPEN_TIME");
        public final static Property Week = new Property(5, String.class, "week", false, "WEEK");
        public final static Property AuthorizeImage = new Property(6, String.class, "authorizeImage", false, "AUTHORIZE_IMAGE");
        public final static Property Date = new Property(7, String.class, "date", false, "DATE");
        public final static Property Time = new Property(8, String.class, "time", false, "TIME");
    };


    public AuthorizeDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorizeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTHORIZE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"IS_AUTHORIZE\" INTEGER NOT NULL ," + // 2: isAuthorize
                "\"IS_OPEN\" INTEGER NOT NULL ," + // 3: isOpen
                "\"OPEN_TIME\" TEXT NOT NULL ," + // 4: openTime
                "\"WEEK\" TEXT NOT NULL ," + // 5: week
                "\"AUTHORIZE_IMAGE\" TEXT NOT NULL ," + // 6: authorizeImage
                "\"DATE\" TEXT NOT NULL ," + // 7: date
                "\"TIME\" TEXT NOT NULL );"); // 8: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTHORIZE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Authorize entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getIsAuthorize() ? 1L: 0L);
        stmt.bindLong(4, entity.getIsOpen() ? 1L: 0L);
        stmt.bindString(5, entity.getOpenTime());
        stmt.bindString(6, entity.getWeek());
        stmt.bindString(7, entity.getAuthorizeImage());
        stmt.bindString(8, entity.getDate());
        stmt.bindString(9, entity.getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Authorize readEntity(Cursor cursor, int offset) {
        Authorize entity = new Authorize( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getShort(offset + 2) != 0, // isAuthorize
            cursor.getShort(offset + 3) != 0, // isOpen
            cursor.getString(offset + 4), // openTime
            cursor.getString(offset + 5), // week
            cursor.getString(offset + 6), // authorizeImage
            cursor.getString(offset + 7), // date
            cursor.getString(offset + 8) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Authorize entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setIsAuthorize(cursor.getShort(offset + 2) != 0);
        entity.setIsOpen(cursor.getShort(offset + 3) != 0);
        entity.setOpenTime(cursor.getString(offset + 4));
        entity.setWeek(cursor.getString(offset + 5));
        entity.setAuthorizeImage(cursor.getString(offset + 6));
        entity.setDate(cursor.getString(offset + 7));
        entity.setTime(cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Authorize entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Authorize entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
