package com.wcsn.irislock.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wcsn.irislock.bean.Alert;

import com.wcsn.irislock.dao.AlertDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alertDaoConfig;

    private final AlertDao alertDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alertDaoConfig = daoConfigMap.get(AlertDao.class).clone();
        alertDaoConfig.initIdentityScope(type);

        alertDao = new AlertDao(alertDaoConfig, this);

        registerDao(Alert.class, alertDao);
    }
    
    public void clear() {
        alertDaoConfig.getIdentityScope().clear();
    }

    public AlertDao getAlertDao() {
        return alertDao;
    }

}
